name: Deploy Proxmox RHEL VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PM_API_URL: ${{ secrets.PM_API_URL }}
      PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
            SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -var="ssh_public_key=$SSH_PUBLIC_KEY"   

      - name: Terraform Apply
        env:
            SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve -var="ssh_public_key=$SSH_PUBLIC_KEY"
